### ISSUE TITLE
xb2xinput and Steelbattaliondriver Hitch a ride?

### ISSUE THREAD

**Issue by Graem117** [caosdoar/SteelBattalionDriver#4]
Hey is it possible to use xb2xinput to get this controller working without turning off authorization? Its been signed and it works with OG xbox controllers.

**Comment by caosdoar** [comment]
You should probably ask the developer of that project, but after having a quick look, I don't think you could use it to use the steel batallion. The steel batallion is not compatible with the xbox original controller.
